### ISSUE TITLE
UI popup doesn't display repos after a while

### ISSUE THREAD

**Issue by Croydon** [crimx/ext-github-release-notifier#1]
While the watch drop down on GitHub still displays the correct watch state, the UI popup only displays the repositories I started to watch within the currect browser session.

After every browser restart, the popup is empty.

________________
Also the part I don't understand yet, if the add-on is noticing a new release how to I get notified? Via browser notifications? Do I need to open the popup manually?

**Edit: This happens on Firefox 57 64-bit on Win10/64bit**

**Comment by crimx** [comment]
Can you offer the repo you are listening to? Might be the repo doesn't have a release yet.

And yes, by browser notifications, since this extension has no server.

**Comment by crimx** [comment]
Now I think it might have something to do with the Firefox's implementation of storage.sync. Did you sign in the Firefox account?

**Comment by Croydon** [comment]
I watched several repositories (~10) and only repos which already have releases as I'm not expecting the others to suddenly use releases.

E.g.:
https://github.com/grpc/grpc/releases
https://github.com/conan-io/conan/releases
https://github.com/google/protobuf/releases

The repos I wachted from two different sessions are gone from the popup, while still being displayed as watched from the GitHub drowndown.

Oddly enough I just tested that again, this time with only one repository and for now it seems to stick after a single restart:

https://github.com/mozilla/webextension-polyfill/releases

> Did you sign in the Firefox account?

Yes

**Comment by crimx** [comment]
Cool. I'll look into that later. Probably just a bug with the popup UI.

**Comment by crimx** [comment]
Still can't reproduce the issue. If you have time, try this:

1. open `about:debugging`
2. find "Release Notifier for Github" and copy the Internal UUID
3. open `moz-extension://[UUID]/popup.html` to view the popup page
4. inspect element and open console
5. with `browser.storage.sync.get(null, console.log)` you should see an array of repos that you're listening to
   with  `browser.storage.local.get(null, console.log)` you should see all the repos' data

**Comment by Croydon** [comment]
Okay. Restart doesn't seem to have an influrence here. The webextension polyfill repo did vanish without restart.

> browser.storage.sync.get(null, console.log) 

The `repos` object is empty here.

> browser.storage.local.get(null, console.log)

The `repos` object contains all repos I have watched (as far as I remember).

**Comment by Croydon** [comment]
I'm using Firefox (and therefore this add-on) on several machines with sync enabled. Do the other instances overwrite the settings in storage.sync maybe? I have only clicked watching only on this one machine here.

**Comment by crimx** [comment]
Yes this should be the bug. I overwrite Storage.sync when there is no value on Storage.get. I'll try to fix it on next release. Though don't expect an instant syncing since brower doesn't specify the timing of sync.

**Comment by crimx** [comment]
Fixed version is shipped. Wait for auto-update and data should be merged seamlessly. But due to the browser sync api is not meant for real-time syncing, you should probably only add subscriptions on one machine. Or wait for the syncing complete before adding subscriptions on other machines.

**Comment by crimx** [comment]
Does the syncing work correctly now? @Croydon

**Comment by Croydon** [comment]
I'm not sure about synching itself right now (will test at a later point and report if it fails).
However, the popup displays now all repositories again.

Thank you!
