### ISSUE TITLE
support more than 100 entries

### ISSUE THREAD

**Issue by gbzret4d** [crimx/ext-github-release-notifier#10]
Hello,
can you support more than 100 entries in the chrome addon?

regards

**Comment by crimx** [comment]
What did you mean? I'm guessing you've exceeded the Chrome storage quota. There's not much I can do about it. With this scale I suggest you setup a server.

**Comment by gbzret4d** [comment]
And how i can increase the chrome limit?

regards

**Comment by crimx** [comment]
Sadly you can't. You can try this alternative <https://releases.netlify.com>.

**Comment by gbzret4d** [comment]
Thank you very much!
Will use the website and your addon!

**Comment by janos** [comment]
I’ve created a project of my own to solve the same problem https://newreleases.io, it has no technical limitations like the one in this issue.

I was not in the need only for GitHub new releases notifications, so this project supports 9 different programming/packaging platforms (GitHub, PyPi, Gems, Docker...). New release notifications can be sent out to your email and/or Slack account and there are several filtering options, even based on regex.
