### ISSUE TITLE
Notifier dropdown options missing

### ISSUE THREAD

**Issue by entroscopy** [crimx/ext-github-release-notifier#12]
The additional dialogue that the extension is supposed to add to the "watch" dropdown seems to be missing. No way to add or remove projects to the extension now. Maybe the new Chrome release broke it? The extension works fine otherwise, scans for and notifies about new releases as intended.

Windows 10
Chrome 69
![capture](https://user-images.githubusercontent.com/30931739/45927266-eff5d100-bf30-11e8-8d4f-36e633869c1c.PNG)

**Comment by crimx** [comment]
Looks like Github has updated the HTML. Fixing it.

**Comment by crimx** [comment]
New version published.
