### ISSUE TITLE
GitHub natively supports watching releases

### ISSUE THREAD

**Issue by salmanulfarzy** [crimx/ext-github-release-notifier#13]
GitHub rolled out watching releases for repositories.

![screenshot from 2018-11-27 23-41-31](https://user-images.githubusercontent.com/10276208/49102144-0bb58480-f29e-11e8-92ce-d3d5e6bea1b3.png)

![screenshot from 2018-11-27 23-39-29](https://user-images.githubusercontent.com/10276208/49102038-baa59080-f29d-11e8-98bb-c756548b2d4c.png)

Though it doesn't allow granular control like this extension.

**Comment by crimx** [comment]
Finally :tada:
