### ISSUE TITLE
Add option to show 'Pre-release' releases

### ISSUE THREAD

**Issue by DcR-NL** [crimx/ext-github-release-notifier#2]
Currently the plugin ignores all releases marked as 'Pre-release'.

**Comment by crimx** [comment]
Actually it's the Github api that ignores the pre-release tags.

With Atom RSS can have the pre-release tags but I think it's slow and doesn't worth the trouble.

**Comment by crimx** [comment]
Should be fixed with v0.2.0 now. Close for now. Feel free to reopen if it doesn't work.
