### ISSUE TITLE
Add option(s) to resize the content

### ISSUE THREAD

**Issue by DcR-NL** [crimx/ext-github-release-notifier#3]
Content is pretty huge with a lot of spacing. I follow a lot of projects and the pop-up has trouble displaying all the content on my 1080p display. The text-size when downscaling to 70% seems to suit me a lot more, but the content area also decreases (it's possible zoom out temporary on my system when using CTRL+Scroll-down).

**Comment by crimx** [comment]
Very sorry I don't have the environment to test against. PRs are welcome.
