### ISSUE TITLE
Link notification to release/tag page

### ISSUE THREAD

**Issue by salmanulfarzy** [crimx/ext-github-release-notifier#4]
It would be great if click on notification redirected to releases page or to tag that triggered notification. I'm not sure whether this is right approach, 

https://github.com/crimx/ext-github-release-notifier/blob/5d2182840cc2215730503892ebc07b5cddd5746a/src/background/main.js#L33

Would it work if we replaced it with,

```js
browser.tabs.create({ url: 'https://github.com/' + name + '/releases' }) 
```

Or with something like `${repoData.tag_name}` ?

BTW Thank you so much for this awesome project, Saves me from notifications bomb when I just want to watch releases 😄

**Comment by crimx** [comment]
Thanks for the advise! I think I'll go for the

```js
browser.tabs.create({ url: 'https://github.com/' + name + '/releases' })
```
