### ISSUE TITLE
Doesn't work with angular repo

### ISSUE THREAD

**Issue by Chippi** [crimx/ext-github-release-notifier#6]
Great plugin! I've used this for a while, but it doesn't work with angular repo.
[angular repo](https://github.com/angular/angular)

![image](https://user-images.githubusercontent.com/6388933/37515883-97090946-290c-11e8-9475-57917ab6ecca.png)

**Comment by crimx** [comment]
It's the issue with GitHub api, which only returns releases that are created from the Github page.

**Comment by crimx** [comment]
If you see the green "Latest release" tag on the release page, that means the api will return the correct version.

**Comment by crimx** [comment]
Should be fixed with v0.2.0 now. Close for now. Feel free to reopen if it doesn't work.
