### ISSUE TITLE
Sync releaser repositories

### ISSUE THREAD

**Issue by falcucci** [crimx/ext-github-release-notifier#7]
So, daily I use two or more notebooks. I would like to always see my repositories synchronized, since I am logged in to Release Notifier.

Is there any way to sync currenctly?

**Comment by crimx** [comment]
It uses the Chrome Extension Sync storage. Not sure about the timing. But I assume the results would be merged successfully with the fix on #1 .

**Comment by falcucci** [comment]
Yes, totally. I'm also using firefox here, surely this would fix the issue.

**Comment by crimx** [comment]
Close for now. Feel free to reopen if it doesn't work.

**Comment by falcucci** [comment]
@crimx when you released the new version of `ext-github-release-notifier`, the popup isn't showing the repositories anymore. Only `ext-github-release-notifier`.

I would be able to confirm in another notebook later about the sync, but why did my repositories disappear from there?

**Comment by falcucci** [comment]
I did wht you said [here](https://github.com/crimx/ext-github-release-notifier/issues/1#issuecomment-355645880) and the results are the same: only `ext-github-release-notifier` in the local storage and I didn't hit the `CLEAR ALL` button accidentally as well :grinning:

**Comment by crimx** [comment]
What do you mean only `ext-github-release-notifier`?  Like only a string?

**Comment by falcucci** [comment]
Sorry I mean only this repository in the popup list:
_____
![captura de tela de 2018-04-18 15 30 02](https://user-images.githubusercontent.com/33763843/38951024-b4edfd7e-431d-11e8-925d-7b5c5b38d62b.png)


```javascript
>>> browser.storage.sync.get(null, console.log)
{
  "repos": [
    "crimx/ext-github-release-notifier"
  ]
}

>>> browser.storage.local.get(null, console.log)
{
  "name": "crimx/ext-github-release-notifier",
  "watching": "all",
  "etag": "W/\"34f4f90d4d3e1f96dd698556615797c2\"",
  "last_modified": "Wed, 18 Apr 2018 17:16:58 GMT",
  "avatar_url": "https://avatars3.githubusercontent.com/u/6882794?v=4",
  "author_url": "https://github.com/crimx",
  "published_at": 1524071818000,
  "html_url": "https://github.com/crimx/ext-github-release-notifier/releases/tag/v0.2.0",
  "tag_name": "v0.2.0",
  "zipball_url": "https://api.github.com/repos/crimx/ext-github-release-notifier/zipball/v0.2.0",
  "tarball_url": "https://api.github.com/repos/crimx/ext-github-release-notifier/tarball/v0.2.0",
  "assets": [
    {
      "browser_download_url": "https://github.com/crimx/ext-github-release-notifier/releases/download/v0.2.0/Release-Notifier-for-Github_v0.2.0.crx",
      "name": "Release-Notifier-for-Github_v0.2.0.crx",
      "icon_name": "package"
    },
    {
      "browser_download_url": "https://github.com/crimx/ext-github-release-notifier/releases/download/v0.2.0/Release-Notifier-for-Github_v0.2.0.xpi",
      "name": "Release-Notifier-for-Github_v0.2.0.xpi",
      "icon_name": "package"
    }
  ]
}
```

**Comment by falcucci** [comment]
I had about 15 repositories in the popup list before.

**Comment by crimx** [comment]
Just found out the bug :joy:. I deserve a slap in the face. https://github.com/crimx/ext-github-release-notifier/blame/master/src/api/storage.js#L109-L111
